<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>

<!-- Modal -->


<!--<div id="modalNewsletter1" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <button class="close" type="button" data-dismiss="modal"> <span>×</span> </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-4 col-sm-5"></div>
                    <div class="col-xs-8 col-sm-7">
                        <h2 class="red" style="font-size: 27px">¡JAMÁS <br>REVISAMOS BURÓ!</h2>
                        <h3 class="blue">RECIBE OFERTAS<br>Y BENEFICIOS.</h3>
                        <div class="block newsletter">
                            <div class="title"><strong><?php /*echo $block->escapeHtml(__('Newsletter')) */?></strong></div>
                            <div class="content">
                            </div>
                        </div>
                    </div>
                </div>


            </div>

        </div>
    </div>
</div>-->

